# Generated by Django 4.2.25 on 2026-02-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuenteFinanciacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=50, verbose_name="Codigo"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "presupuesto_asignado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Presupuesto Asignado",
                    ),
                ),
                ("vigencia", models.IntegerField(default=2026)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fuente de Financiacion",
                "verbose_name_plural": "Fuentes de Financiacion",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PACProgramado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(default=2026)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("GASTO", "Gasto")],
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALDO_INICIAL", "Saldo Inicial"),
                            ("INGRESO_CORRIENTE", "Ingresos Corrientes"),
                            ("INGRESO_CAPITAL", "Ingresos de Capital"),
                            ("FUNCIONAMIENTO", "Funcionamiento"),
                            ("INVERSION", "Inversion"),
                            ("DEUDA", "Servicio a la Deuda"),
                            ("RESERVAS", "Reservas Presupuestales"),
                            ("CUENTAS_POR_PAGAR", "Cuentas por Pagar"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "codigo_rubro",
                    models.CharField(max_length=200, verbose_name="Codigo Rubro"),
                ),
                (
                    "nombre_rubro",
                    models.CharField(max_length=500, verbose_name="Nombre Rubro"),
                ),
                (
                    "fuente_financiacion",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Fuente de Financiacion",
                    ),
                ),
                (
                    "apropiacion_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Inicial",
                    ),
                ),
                (
                    "adiciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "reduccion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "creditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "contracreditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "apropiacion_definitiva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Definitiva",
                    ),
                ),
                (
                    "enero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "febrero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "marzo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "abril",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "mayo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "junio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "julio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "agosto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "septiembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "octubre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "noviembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "diciembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("es_subtotal", models.BooleanField(default=False)),
                (
                    "fila_excel",
                    models.IntegerField(default=0, help_text="Fila original del Excel"),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PAC Programado",
                "verbose_name_plural": "PAC Programados",
                "ordering": ["fila_excel", "tipo", "codigo_rubro"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PACEjecutadoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(default=2026)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("GASTO", "Gasto")],
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALDO_INICIAL", "Saldo Inicial"),
                            ("INGRESO_CORRIENTE", "Ingresos Corrientes"),
                            ("INGRESO_CAPITAL", "Ingresos de Capital"),
                            ("FUNCIONAMIENTO", "Funcionamiento"),
                            ("INVERSION", "Inversion"),
                            ("DEUDA", "Servicio a la Deuda"),
                            ("RESERVAS", "Reservas Presupuestales"),
                            ("CUENTAS_POR_PAGAR", "Cuentas por Pagar"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "codigo_rubro",
                    models.CharField(max_length=200, verbose_name="Codigo Rubro"),
                ),
                (
                    "nombre_rubro",
                    models.CharField(max_length=500, verbose_name="Nombre Rubro"),
                ),
                (
                    "fuente_financiacion",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Fuente de Financiacion",
                    ),
                ),
                (
                    "apropiacion_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Inicial",
                    ),
                ),
                (
                    "adiciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "reduccion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "creditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "contracreditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "apropiacion_definitiva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Definitiva",
                    ),
                ),
                (
                    "enero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "febrero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "marzo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "abril",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "mayo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "junio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "julio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "agosto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "septiembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "octubre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "noviembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "diciembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("es_subtotal", models.BooleanField(default=False)),
                (
                    "fila_excel",
                    models.IntegerField(default=0, help_text="Fila original del Excel"),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PAC Ejecutado Pago",
                "verbose_name_plural": "PAC Ejecutados Pagos",
                "ordering": ["fila_excel", "tipo", "codigo_rubro"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PACEjecutadoCompromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(default=2026)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("GASTO", "Gasto")],
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALDO_INICIAL", "Saldo Inicial"),
                            ("INGRESO_CORRIENTE", "Ingresos Corrientes"),
                            ("INGRESO_CAPITAL", "Ingresos de Capital"),
                            ("FUNCIONAMIENTO", "Funcionamiento"),
                            ("INVERSION", "Inversion"),
                            ("DEUDA", "Servicio a la Deuda"),
                            ("RESERVAS", "Reservas Presupuestales"),
                            ("CUENTAS_POR_PAGAR", "Cuentas por Pagar"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "codigo_rubro",
                    models.CharField(max_length=200, verbose_name="Codigo Rubro"),
                ),
                (
                    "nombre_rubro",
                    models.CharField(max_length=500, verbose_name="Nombre Rubro"),
                ),
                (
                    "fuente_financiacion",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Fuente de Financiacion",
                    ),
                ),
                (
                    "apropiacion_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Inicial",
                    ),
                ),
                (
                    "adiciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "reduccion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "creditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "contracreditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "apropiacion_definitiva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Definitiva",
                    ),
                ),
                (
                    "enero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "febrero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "marzo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "abril",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "mayo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "junio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "julio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "agosto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "septiembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "octubre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "noviembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "diciembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("es_subtotal", models.BooleanField(default=False)),
                (
                    "fila_excel",
                    models.IntegerField(default=0, help_text="Fila original del Excel"),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PAC Ejecutado Compromiso",
                "verbose_name_plural": "PAC Ejecutados Compromisos",
                "ordering": ["fila_excel", "tipo", "codigo_rubro"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CargaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AIM_INICIAL", "AIM Inicial"),
                            ("PROGRAMADO", "PAC Programado"),
                            ("EJECUTADO_COMPROMISO", "PAC Ejecutado - Compromisos"),
                            ("EJECUTADO_PAGO", "PAC Ejecutado - Pagos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("archivo", models.FileField(upload_to="importaciones/")),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("registros_cargados", models.IntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga de Archivo",
                "verbose_name_plural": "Cargas de Archivos",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="AIMInicial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(default=2026)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("GASTO", "Gasto")],
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALDO_INICIAL", "Saldo Inicial"),
                            ("INGRESO_CORRIENTE", "Ingresos Corrientes"),
                            ("INGRESO_CAPITAL", "Ingresos de Capital"),
                            ("FUNCIONAMIENTO", "Funcionamiento"),
                            ("INVERSION", "Inversion"),
                            ("DEUDA", "Servicio a la Deuda"),
                            ("RESERVAS", "Reservas Presupuestales"),
                            ("CUENTAS_POR_PAGAR", "Cuentas por Pagar"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "codigo_rubro",
                    models.CharField(max_length=200, verbose_name="Codigo Rubro"),
                ),
                (
                    "nombre_rubro",
                    models.CharField(max_length=500, verbose_name="Nombre Rubro"),
                ),
                (
                    "fuente_financiacion",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Fuente de Financiacion",
                    ),
                ),
                (
                    "apropiacion_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Inicial",
                    ),
                ),
                (
                    "adiciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "reduccion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "creditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "contracreditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "apropiacion_definitiva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aprop. Definitiva",
                    ),
                ),
                (
                    "enero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "febrero",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "marzo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "abril",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "mayo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "junio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "julio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "agosto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "septiembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "octubre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "noviembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "diciembre",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("es_subtotal", models.BooleanField(default=False)),
                (
                    "fila_excel",
                    models.IntegerField(default=0, help_text="Fila original del Excel"),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AIM Inicial",
                "verbose_name_plural": "AIM Iniciales",
                "ordering": ["fila_excel", "tipo", "codigo_rubro"],
                "abstract": False,
            },
        ),
    ]
